#!/bin/bash


#############################
# Preliminary data setup step
#############################


# --------------------> Enable debug logging  
export PS4=' $SECONDS + '
#set -x

pgm_jobs=stofs_3d_atl/JSTOFS_3D_ATL_POST_II
echo; echo "Running jobs script: ${pgm_jobs}"; echo


# YMD_CURRENT_DATE
if [ $# -ne 0 ] && [ -n "$1" ]; then

  export YMD_CURRENT_DATE=$1
  echo; echo "Your input, argu[0]: YMD_CURRENT_DATE = ${YMD_CURRENT_DATE}"; echo

else

  YMD_CURRENT_DATE=`date +%Y%m%d`
  #YMD_CURRENT_DATE=`date --date yesterday +%Y%m%d` 
  
  echo; echo "YMD_CURRENT_DATE = ${YMD_CURRENT_DATE}"; echo

fi

# --------------------> Define process id info
export job_name=jobs_post_processing

export pid=$$
export outid=${job_name}
export jobid=${outid}.o${pid}
export pgmout=OUTPUT.${pid}

#--------------------> Meta data
export envir=${envir:-test}

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-NO}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export NET=${NET:-stofs3d}
export RUN=${RUN:-stofs_3d_atl}

export stofs_3d_atl_ver=v1.1.0


# -------------------> Define base (root) directoris
#export HOMEstofs=/lfs/h1/nos/estofs/noscrub/Zizang.Yang/STOFS_3D_nco

ROOT=
export ROOT=${HOMEstofs}

COMROOT=
export COMROOT=${COMROOT:-${ROOT}/com/stofs/v1.1}

DATAROOT=
export DATAROOT=${HOMEstofs}/work/${RUN}

export COMPATH=
export COMPATH=${COMPATH:-/lfs/h1/ops/prod/com}


# -------------------> Define date/cycle  variables
export cyc=12
export cycle=t${cyc}z
#export N_DAYS_MODEL_RUN_PERIOD=3.0


export PDY=${YMD_CURRENT_DATE}

export KEEPDATA="YES"

DATA=
export DATA=${DATA:-${DATAROOT}/run_$YMD_CURRENT_DATE}

cd ${DATAROOT};
ln -sf run_${YMD_CURRENT_DATE}  post.${pid}
cd $DATA

# pre-requisite for setpdy.sh: existed $DATA!
setpdy.sh
. ./PDY

export PDYHH=${PDY}$cyc
export PDYHH_FCAST_BEGIN=$PDYHH
export PDYHH_FCAST_END=$($NDATE 24 $PDYHH)
export PDYHH_NCAST_BEGIN=$($NDATE -24 $PDYHH)

echo 
echo PDYHH = $PDYHH
echo PDYHH_FCAST_BEGIN =  $PDYHH_FCAST_BEGIN
echo PDYHH_FCAST_END = $PDYHH_FCAST_END
echo PDYHH_NCAST_BEGIN = $PDYHH_NCAST_BEGIN

echo DATA = $DATA


#################################################
# Execution directory structure
# If dev, run config file to get input parameters
#################################################

export JOBstofs3d=${JOBstofs3d:-$HOMEstofs/jobs/${RUN}}
export EXECstofs3d=${EXECstofs3d:-$HOMEstofs/exec/${RUN}}
export FIXstofs3d=${FIXstofs3d:-$HOMEstofs/fix/${RUN}}
export PARMstofs3d=${PARMstofs3d:-$HOMEstofs/parm/${RUN}}
export SORCstofs3d=${SORCstofs3d:-$HOMEstofs/sorc/${RUN}}
export SCRIstofs3d=${SCRIstofs3d:-$HOMEstofs/scripts/${RUN}}
export USHstofs3d=${USHstofs3d:-$HOMEstofs/ush/${RUN}}
export ECFstofs3d=${ECFstofs3d:-$HOMEstofs/ecf/${RUN}}

export PYstofs3d=${PYstofs3d:-$USHstofs3d/pysh}


# ---------------------> Define jlog file
# export jlogfile=${jlogfile:-${DATA}/jlogfile.${PDY}.${jobid}}
export jlogfile=${jlogfile:-${DATA}/jlogfile.${PDY}.${pid}}

# ---------------------> Define ROOT/COM/COMIN/COMOUT
COMIN=
export COMIN=${COMIN:-${COMROOT}/${RUN}.${PDY}}

export COMOUT=
export COMOUT=${COMOUT:-${COMROOT}/${RUN}.${PDY}}

COMOUTrerun=
export COMOUTrerun=${COMOUTrerun:-${COMROOT}/${RUN}.${PDY}/rerun}

mkdir -p $COMIN $COMOUT $COMOUTrerun

#export COMOUTlog=${COMOUTlog:-${COMOUT}/logs}

# ------------------------------------------------------------------->
# Execute script: 

   ${SCRIstofs3d}/exstofs_3d_atl_post_2.sh


# ------------------------------------------------------------------->

if [ -f $pgmout ]; then
    cat $pgmout
fi


if [ "${KEEPDATA}" != YES ]; then
	rm  -rf $DATA
fi


postmsg $jlogfile "$0 completed normally"

