#!/bin/bash


#############################
# Preliminary data setup step
#############################


# --------------------> Enable debug logging  
export PS4=' $SECONDS + '
#set -x


pgm_jobs=JSTOFS_3D_ATL_NOW_FORECAST
echo; echo "Running jobs script: ${pgm_jobs}"; echo


# YMD_CURRENT_DATE
if [ $# -ne 0 ] && [ -n "$1" ]; then

  export YMD_CURRENT_DATE=$1
  echo; echo "Your input, argu[0]: YMD_CURRENT_DATE = ${YMD_CURRENT_DATE}"; echo

else

  YMD_CURRENT_DATE=`date +%Y%m%d`
  #YMD_CURRENT_DATE=`date --date yesterday +%Y%m%d` 
  
  echo; echo "YMD_CURRENT_DATE = ${YMD_CURRENT_DATE}"; echo

fi



# --------------------> Define process id info
export job_name=jobs_prep_inputs
export pid=$$
export outid=${job_name}
export jobid=${outid}.o${pid}
export pgmout=OUTPUT.${pid}


#--------------------> Meta data
export envir=${envir:-test}

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-NO}
export SENDDBN=${SENDDBN:-NO}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export NET=${NET:-stofs3d}
export RUN=${RUN:-stofs_3d_atl}
export RUN_ENVIR=${RUN_ENVIR:-test}

export stofs_3d_atl_ver=v2.0


# -------------------> Define base (root) directoris

ROOT=
export ROOT=${HOMEstofs}

COMROOT=
export COMROOT=${COMROOT:-${ROOT}/com/stofs/v1.1}

DATAROOT=
export DATAROOT=${HOMEstofs}/work/${RUN}

export COMPATH=
export COMPATH=${COMPATH:-/lfs/h1/ops/prod/com}


# -------------------> Define date/cycle  variables
export cyc=12
export cycle=t${cyc}z
export N_DAYS_MODEL_RUN_PERIOD=3.0


export PDY=${YMD_CURRENT_DATE}


# YES: not to delete: data needed for post processing
export KEEPDATA="YES"  

DATA=
export DATA=${DATA:-${DATAROOT}/run_$YMD_CURRENT_DATE}
mkdir -p $DATA; 

cd ${DATAROOT};
ln -sf run_${YMD_CURRENT_DATE}  run.${pid}
cd $DATA

# pre-requisite for setpdy.sh: existed $DATA!
setpdy.sh
. ./PDY

export PDYHH=${PDY}$cyc
export PDYHH_FCAST_BEGIN=$PDYHH
export PDYHH_FCAST_END=$($NDATE 24 $PDYHH)
export PDYHH_NCAST_BEGIN=$($NDATE -24 $PDYHH)

echo 
echo PDYHH = $PDYHH
echo PDYHH_FCAST_BEGIN =  $PDYHH_FCAST_BEGIN
echo PDYHH_FCAST_END = $PDYHH_FCAST_END
echo PDYHH_NCAST_BEGIN = $PDYHH_NCAST_BEGIN


# --------------------> load modules
# load modules
# module purge
# source /u/Zizang.Yang/module_load_zy


# --------------------> system utility programs
# export python=/apps/spack/python/3.8.6/intel/19.1.3.304/pjn2nzkjvqgmjw4hmyz43v5x4jbxjzpk/bin/python



#################################################
# Execution directory structure
# If dev, run config file to get input parameters
#################################################

export JOBstofs3d=${JOBstofs3d:-$HOMEstofs/jobs/${RUN}}
export EXECstofs3d=${EXECstofs3d:-$HOMEstofs/exec/${RUN}}
export FIXstofs3d=${FIXstofs3d:-$HOMEstofs/fix/${RUN}}
export PARMstofs3d=${PARMstofs3d:-$HOMEstofs/parm/${RUN}}
export SORCstofs3d=${SORCstofs3d:-$HOMEstofs/sorc/${RUN}}
export SCRIstofs3d=${SCRIstofs3d:-$HOMEstofs/scripts/${RUN}}
export USHstofs3d=${USHstofs3d:-$HOMEstofs/ush/${RUN}}
export ECFstofs3d=${ECFstofs3d:-$HOMEstofs/ecf/${RUN}}

#export NCLstofs3d=${NCLstofs3d:-$HOMEstofs/ncl}
export PYstofs3d=${PYstofs3d:-$HOMEstofs/pysh/${RUN}}


# ---------------------> Define jlog file
# export jlogfile=${jlogfile:-${DATA}/jlogfile.${PDY}.${jobid}}
export jlogfile=${jlogfile:-${DATA}/jlogfile.${PDY}.${pid}}


# ---------------------> Define ROOT/COM/COMIN/COMOUT
COMIN=
export COMIN=${COMIN:-${COMROOT}/${RUN}.${PDY}}

export COMOUT=
export COMOUT=${COMOUT:-${COMROOT}/${RUN}.${PDY}}

COMOUTrerun=
export COMOUTrerun=${COMOUTrerun:-${COMROOT}/${RUN}.${PDY}/rerun}

mkdir -p $COMIN $COMOUT $COMOUTrerun

#export COMOUTlog=${COMOUTlog:-${COMOUT}/logs}

#rm -rf $COMIN $COMOUT $COMOUTlog
#mkdir -p $COMIN $COMOUT $COMOUTlog


export COMOUT_PREV=
export COMOUT_PREV=${COMOUT_PREV:-${COMROOT}/${RUN}.${PDYm1}}


# --------------> Define forcing data sources dir
export COMINgfs=
export COMINgfs=${COMINgfs:-${COMPATH}/gfs/v16.2}

# HRRR:
export COMINhrrr=
export COMINhrrr=${COMINhrrr:-${COMPATH}/hrrr/v4.1}

# RTOFS:
export COMINrtofs=
export COMINrtofs=${COMINrtofs:-${COMPATH}/rtofs/v2.3}

#export COMINnwm=${COMINnwm:-/gpfs/hps/nco/ops/com/nwm/prod/nwm.${PDY}/medium_range_mem1
export COMINnwm=
export COMINnwm=${COMINnwm:-${COMPATH}/nwm/v2.2}



#--------------------------------------------->
# Conduct nowcast/forecast simulations   
#   copy input/forcing files
#   conduct: mpiexec SCHISM model run
#---------------------------------------

${SCRIstofs3d}/stofs_3d_atl_now_forecast.sh   >> $pgmout 2> errfile


  export err=$?; err_chk
  pgm=$fn_exe_gen_hotstart

  if [ $err -eq 0 ]; then
    msg=`echo $pgm  completed normally`
    echo $msg
    echo $msg >> $pgmout

  else
    msg=`echo $pgm did not complete normally`
    echo $msg
    echo $msg >> $pgmout
  fi


if [ -f $pgmout ]; then
    cat $pgmout
fi


#if [ "${KEEPDATA}" != YES ]; then
#	rm  -rf $DATA
#fi



postmsg $jlogfile "$0 completed normally"



