#!/bin/sh

#############################
# Preliminary data setup step
#############################
set -xa

# ##############################
# SET SHELL PROCESSING VARIABLES
# ##############################
export PS4='$SECONDS + '
date

##########################
# Specify NET and RUN name
##########################
export NET=${NET:-stofs}
export RUN=${RUN:-stofs_2d_glo}

export RUN_ENVIR=${RUN_ENVIR:-prod}

##########################################################
# obtain unique process id (pid) and make temp directories
##########################################################
export pid=$$
export DATAROOT=${DATAROOT:-/lfs/h1/ops/${RUN_ENVIR}/tmp}
export DATA=${DATA:-${DATAROOT}/${jobid}}

mkdir $DATA
cd $DATA

export cycle=t${cyc}z

##################
# File To Log Msgs
##################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${jobid}}

#####################################
# Determine Job Output Name on System
#####################################
export pgmout="OUTPUT.$$"

##############################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##############################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-STOFS_NETCDF}

###################################
# Set up the UTILITIES
###################################
export EXECstofs=${EXECstofs:-$HOMEstofs/exec/${RUN}}
export FIXstofs=${FIXstofs:-$HOMEstofs/fix/${RUN}}
export PARMstofs=${PARMstofs:-$HOMEstofs/parm/${RUN}}
export SORCstofs=${SORCstofs:-$HOMEstofs/sorc/${RUN}}
export SCRIstofs=${SCRIstofs:-$HOMEstofs/scripts/${RUN}}
export USHstofs=${USHstofs:-$HOMEstofs/ush/${RUN}}

#Run setpdy and initialize PDY variables
setpdy.sh

. ./PDY

###############################################
# Define input and output com directories
###############################################
export COM=${COM:-$(compath.py -o ${NET}/${stofs_ver})}
export COMIN=${COMIN:-$(compath.py ${envir}/${NET}/${stofs_ver})/${RUN}.${PDY}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${stofs_ver}/${RUN}.${PDY})}
export COMGES=${COMGES:-$COM/nwges}
export COMOUTrerun=${COMOUTrerun:-${COMOUT}/rerun}
mkdir -p -m 775 $COM $COMIN $COMOUT $COMGES $COMOUTrerun

env
date

#############################################
# Execute the scrpit.
  $SCRIstofs/exstofs_2d_glo_prep_forecast2.sh 
#############################################

if [ -f $pgmout ]; then
    cat $pgmout
fi

postmsg $jlogfile "$0 completed normally"

cd ${DATAROOT}
if [ ${KEEPDATA}:-YES} = NO ] ; then rm -rf $DATA ; fi

date
