#!/bin/bash


#############################
# Preliminary data setup step
#############################
export PS4=' $SECONDS + '
set -x

date

##########################
# Specify NET and RUN name
##########################
export NET=${NET:-stofs}
export RUN=${RUN:-stofs_3d_atl}

##########################################################
# obtain unique process id (pid) and make temp directories
##########################################################
export DATA=${DATA:-${DATAROOT}/stofs_3d_atl_run_${cyc}_${envir}_${stofs_ver}}

mkdir $DATA
cd $DATA


export cycle=t${cyc}z

##################
# File To Log Msgs
##################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${jobid}}

#####################################
# Determine Job Output Name on System
#####################################
export pgmout="OUTPUT.$$"

##############################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##############################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-NO}
export SENDDBN=${SENDDBN:-NO}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}



export JOBstofs3d=${JOBstofs3d:-$HOMEstofs/jobs/${RUN}}
export EXECstofs3d=${EXECstofs3d:-$HOMEstofs/exec/${RUN}}
export FIXstofs3d=${FIXstofs3d:-$HOMEstofs/fix/${RUN}}
export PARMstofs3d=${PARMstofs3d:-$HOMEstofs/parm/${RUN}}
export SORCstofs3d=${SORCstofs3d:-$HOMEstofs/sorc/${RUN}}
export SCRIstofs3d=${SCRIstofs3d:-$HOMEstofs/scripts/${RUN}}
export USHstofs3d=${USHstofs3d:-$HOMEstofs/ush/${RUN}}
export ECFstofs3d=${ECFstofs3d:-$HOMEstofs/ecf/${RUN}}

export PYstofs3d=${PYstofs3d:-$USHstofs3d/pysh}

export N_DAYS_MODEL_RUN_PERIOD=3.0

# pre-requisite for setpdy.sh: existed $DATA!
setpdy.sh
. ./PDY

export PDYHH=${PDY}$cyc
export PDYHH_FCAST_BEGIN=$PDYHH
export PDYHH_FCAST_END=$($NDATE 24 $PDYHH)
export PDYHH_NCAST_BEGIN=$($NDATE -24 $PDYHH)

###############################################
# Define input and output com directories
###############################################
export COMIN=${COMIN:-$(compath.py ${envir}/${NET}/${stofs_ver})/${RUN}.${PDY}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${stofs_ver})/${RUN}.${PDY}}
export COMOUTrerun=${COMOUTrerun:-$(compath.py -o ${NET}/${stofs_ver})/${RUN}.${PDY}/rerun}
export COMOUT_PREV=${COMOUT_PREV:-$(compath.py ${envir}/${NET}/${stofs_ver})/${RUN}.${PDYm1}}

mkdir -p $COMOUT $COMOUTrerun

export COMINgfs=${COMINgfs:-$(compath.py gfs/$gfs_ver)}
export COMINhrrr=${COMINhrrr:-$(compath.py hrrr/$hrrr_ver)}
export COMINrtofs=${COMINrtofs:-$(compath.py rtofs/$rtofs_ver)}
export COMINnwm=${COMINnwm:-$(compath.py nwm/$nwm_ver)}

########################################
# Conduct nowcast/forecast simulations   
#   copy input/forcing files
#   conduct: mpiexec SCHISM model run
########################################

${SCRIstofs3d}/exstofs_3d_atl_now_forecast.sh   >> $pgmout 2> errfile

  export err=$?; err_chk
  pgm=$fn_exe_gen_hotstart

  if [ $err -eq 0 ]; then
    msg=`echo $pgm  completed normally`
    echo $msg
    echo $msg >> $pgmout

  else
    msg=`echo $pgm did not complete normally`
    echo $msg
    echo $msg >> $pgmout
  fi


if [ -f $pgmout ]; then
    cat $pgmout
fi

postmsg $jlogfile "$0 completed normally"

export KEEPDATA=YES

if [ "${KEEPDATA}" != YES ]; then
	rm  -rf $DATA
fi

date
